name = "taleium"
account_id = "749e8e915104c226e492df9c5bb31444"
compatibility_date = "2024-01-01"
main = "src/worker/index.ts"

[vars]
# ANTHROPIC_API_KEY set via: wrangler secret put ANTHROPIC_API_KEY

[[kv_namespaces]]
binding = "ARTICLE_CACHE"
id = "bf1b6840f5764f91b9ea49b2015e97e8"
preview_id = "4009bf44b55e4364a5674856e12fd84f"

[[d1_databases]]
binding = "DB"
database_name = "taleium-meta"
database_id = "93aeccbf-35ec-4a3b-bc2c-f6fb91bb6a90"

[site]
bucket = "./dist"
