import { Link } from 'react-router-dom';

export default function Terms() {
  return (
    <main className="legal-page page-container">
      <h1 className="legal-title">Terms of Service</h1>
      <p className="legal-updated">Last updated: 22 March 2026</p>

      <section className="legal-section">
        <h2>About Taleium</h2>
        <p>
          Taleium is a collaborative story creation service operated by <strong>Kabooly Ltd</strong>,
          a company registered in England and Wales (company number 15653819). Our registered address
          is 23 Carisbrooke House, Seven Kings Way, Kingston Upon Thames, KT2 5BS, United Kingdom.
        </p>
        <p>
          By creating an account or using Taleium, you agree to these terms. If you do not agree, please do not use the service.
        </p>
      </section>

      <section className="legal-section">
        <h2>Accounts</h2>
        <ul>
          <li>You must be at least 18 years old to create an account.</li>
          <li>Accounts are intended for use by a parent or guardian. Children may use Taleium under adult supervision on the same device and session.</li>
          <li>You are responsible for maintaining the security of your account and password.</li>
          <li>You must provide accurate information when creating your account.</li>
          <li>We reserve the right to suspend or terminate accounts that violate these terms.</li>
        </ul>
      </section>

      <section className="legal-section">
        <h2>The service</h2>
        <p>
          Taleium allows you to create stories collaboratively, chapter by chapter, with AI assistance.
          The AI generates story text based on your prompts and creative direction.
        </p>
        <ul>
          <li><strong>Free tier:</strong> 1 book, up to 3 chapters per book.</li>
          <li><strong>Premium:</strong> unlimited books and chapters for &pound;4.99 per month.</li>
        </ul>
        <p>
          We aim to keep Taleium available and reliable, but we do not guarantee uninterrupted access.
          We may modify, suspend, or discontinue features with reasonable notice.
        </p>
      </section>

      <section className="legal-section">
        <h2>Your content</h2>
        <p>
          You retain ownership of the prompts and creative direction you provide. AI-generated story
          content is produced at your direction and you may use it as you wish.
        </p>
        <p>
          By making a story public or sharing it via a link, you grant other Taleium users permission
          to read that story. You can change visibility or delete your stories at any time.
        </p>
        <p>
          We do not claim ownership of your content. We store it solely to provide the service to you.
        </p>
      </section>

      <section className="legal-section">
        <h2>AI-generated content</h2>
        <p>
          Stories are generated by AI (Anthropic Claude) and may occasionally produce unexpected or
          inaccurate content. While we configure the AI for age-appropriate output based on your
          selected age range, we cannot guarantee that all generated content will be perfectly suitable.
          We recommend that parents review stories, particularly for younger children.
        </p>
        <p>
          AI-generated content should not be relied upon as factual information.
        </p>
      </section>

      <section className="legal-section">
        <h2>Acceptable use</h2>
        <p>You agree not to use Taleium to:</p>
        <ul>
          <li>Create content that is illegal, harmful, abusive, or promotes violence</li>
          <li>Attempt to generate content that is sexually explicit or inappropriate for children</li>
          <li>Harass, impersonate, or harm other users</li>
          <li>Interfere with or disrupt the service</li>
          <li>Use automated tools to access the service (scraping, bots, etc.)</li>
          <li>Circumvent free tier limits or payment requirements</li>
        </ul>
        <p>
          We reserve the right to remove content and suspend accounts that violate these rules.
        </p>
      </section>

      <section className="legal-section">
        <h2>Payments and subscriptions</h2>
        <p>
          Premium subscriptions are billed monthly at &pound;4.99 via Stripe. By subscribing, you
          authorise recurring monthly payments until you cancel.
        </p>
        <ul>
          <li>You can cancel at any time through the account page. Your access continues until the end of the current billing period.</li>
          <li>We do not offer refunds for partial months.</li>
          <li>If payment fails, your account may be downgraded to the free tier.</li>
          <li>Prices may change with 30 days' notice.</li>
        </ul>
      </section>

      <section className="legal-section">
        <h2>Limitation of liability</h2>
        <p>
          To the fullest extent permitted by law, Kabooly Ltd shall not be liable for any indirect,
          incidental, or consequential damages arising from your use of Taleium. Our total liability
          is limited to the amount you have paid us in the 12 months preceding any claim.
        </p>
        <p>
          Nothing in these terms excludes or limits our liability for death or personal injury
          caused by negligence, fraud, or any other liability that cannot be excluded by law.
        </p>
      </section>

      <section className="legal-section">
        <h2>Intellectual property</h2>
        <p>
          The Taleium name, logo, design, and underlying code are owned by Kabooly Ltd.
          You may not copy, modify, or distribute any part of the Taleium platform without permission.
        </p>
        <p>
          Book cover images are sourced from Wikimedia Commons and are used under their respective licences.
          Attribution is displayed alongside each image.
        </p>
      </section>

      <section className="legal-section">
        <h2>Governing law</h2>
        <p>
          These terms are governed by the laws of England and Wales. Any disputes will be subject
          to the exclusive jurisdiction of the courts of England and Wales.
        </p>
      </section>

      <section className="legal-section">
        <h2>Changes to these terms</h2>
        <p>
          We may update these terms from time to time. We will update the "last updated" date
          at the top of this page. Continued use of Taleium after changes constitutes acceptance
          of the updated terms.
        </p>
      </section>

      <section className="legal-section">
        <h2>Contact us</h2>
        <p>
          If you have any questions about these terms, contact us at{' '}
          <a href="mailto:hello@kabooly.com">hello@kabooly.com</a>.
        </p>
      </section>

      <div className="legal-nav">
        <Link to="/privacy">Privacy Policy</Link>
      </div>
    </main>
  );
}
